apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hello-hostname-deployment
  labels:
    app: node-hello-hostname
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-hello-hostname
  template:
    metadata:
      labels:
        app: node-hello-hostname
    spec:
      containers:
      - name: node-hello-hostname
        image: fra.ocir.io/frol67eoawud/node-hello-hostname-repo:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: node-hello-hostname-service
spec:
  selector:
    app: node-hello-hostname
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
